# -*- coding: utf-8 -*-
"""Langgraph_orchestrator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3vhmsiy62oStXGEOjKlLZONM_Za_Lzk
"""

from langgraph.graph import StateGraph, END, START
from langgraph.types import Send
from typing import TypedDict, Annotated, List
from pydantic.v1 import BaseModel, Field
import operator
import os

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI

if "GOOGLE_API_KEY" not in os.environ:
    raise RuntimeError(
        "Set GOOGLE_API_KEY in your environment (e.g. via Colab secrets) before running."
    )

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)


# Schemas
class Dish(BaseModel):
    name: str = Field(description="Name of the dish")
    ingredients: List[str] = Field(description="Ingredients of the dish")
    location: str = Field(
        description="The cuisine or cultural origin of the dish (eg. Italian, Indian, Mexican)."
    )


class Dishes(BaseModel):
    section: List[Dish] = Field(
        description="A list of dishes with their ingredients and cuisine origin"
    )


class State(TypedDict):
    meals: str
    section: List[Dish]
    completed_menu: Annotated[List[str], operator.add]
    final_menu_guide: str


class WorkerState(TypedDict):
    section: Dish
    completed_menu: List[str]


# Orchestrator LLM: breaks meals into structured dishes
# NOTE: PydanticOutputParser.get_format_instructions() returns text containing

parser = PydanticOutputParser(pydantic_object=Dishes)


def orchestrator(state: State):
    """Generates a structured dish list from the given meals."""
    meals = state["meals"]
    print("DEBUG[orchestrator] meals:", repr(meals))
    if not meals or not meals.strip():
        raise ValueError("orchestrator received empty 'meals' input")

    format_instructions = parser.get_format_instructions()
    prompt_text = (
        "You are an expert in culinary arts. Your task is to identify individual "
        "dishes from the user's request and present them in a structured JSON format. "
        f"Generate a list of dishes for the following meals: {meals}.\n"
        "Tip: Make sure to output JSON that adheres to the following schema:\n"
        f"{format_instructions}"
    )
    print("DEBUG[orchestrator] prompt_text length:", len(prompt_text))
    print("DEBUG[orchestrator] prompt_text preview:", repr(prompt_text[:300]))

    response = llm.invoke(prompt_text)
    print("DEBUG[orchestrator] raw response:", repr(response))
    print("DEBUG[orchestrator] response.content:", repr(getattr(response, "content", None)))

    dish_description = parser.invoke(response)
    print("DEBUG[orchestrator] parsed dishes:", dish_description)
    return {"section": dish_description.section}


def assign_workers(state: State):
    """Fan out: one Send(...) per dish, routed to chef_worker."""
    print("DEBUG[assign_workers] section list:", state["section"])
    sends = [Send("chef_worker", {"section": s}) for s in state["section"]]
    print("DEBUG[assign_workers] num sends:", len(sends))
    return sends

#
# Worker LLM: writes detailed cooking instructions per dish ---
# same risk as the orchestrator prompt - ChatPromptTemplate does f-string
# style substitution. Here it's lower-risk (no JSON-schema braces), but to fully
# rule it out as a cause of empty-content responses under parallel Send() fan-out,
# build the chef prompt as a plain string too, and call llm.invoke() directly
# instead of going through the ChatPromptTemplate pipe.
def chef_worker(state: WorkerState):
    """Builds one section of the menu for a single dish."""
    section = state["section"]
    print("DEBUG[chef_worker] section:", repr(section))

    prompt_text = (
        f"You are a world class chef from {section.location}.\n\n"
        f"Please introduce yourself briefly and present a detailed walkthrough for "
        f"preparing the dish: {section.name}.\n"
        "Your response should include:\n"
        "- Start with hello, your name, and culinary background\n"
        "- A clear list of preparation steps\n"
        f"Use the following ingredients: {', '.join(section.ingredients)}."
    )
    print("DEBUG[chef_worker] prompt_text length:", len(prompt_text))

    try:
        meal_plan = llm.invoke(prompt_text)
    except Exception as e:
        print("DEBUG[chef_worker] EXCEPTION during llm.invoke:", type(e).__name__, str(e))
        raise

    print("DEBUG[chef_worker] meal_plan:", repr(meal_plan))
    print("DEBUG[chef_worker] meal_plan.content:", repr(getattr(meal_plan, "content", None)))

    content = meal_plan.content
    if not content or not str(content).strip():
        print("DEBUG[chef_worker] WARNING: empty content! finish_reason =",
              meal_plan.response_metadata.get("finish_reason") if hasattr(meal_plan, "response_metadata") else None)
        content = f"[No content returned for {section.name} -- finish_reason: {getattr(meal_plan, 'response_metadata', {}).get('finish_reason')}]"

    return {"completed_menu": [content]}


def synthesizer(state: State):
    """Joins all completed dish writeups into the final guide."""
    completed_sections = state["completed_menu"]
    final_menu_guide = "\n\n.....\n\n".join(completed_sections)
    return {"final_menu_guide": final_menu_guide}


#Build graph
orchestrator_worker_builder = StateGraph(State)

orchestrator_worker_builder.add_node("orchestrator", orchestrator)
orchestrator_worker_builder.add_node("chef_worker", chef_worker)
orchestrator_worker_builder.add_node("synthesizer", synthesizer)

orchestrator_worker_builder.add_edge(START, "orchestrator")

# Conditional edge required for Send(...) fan-out to actually reach chef_worker.
orchestrator_worker_builder.add_conditional_edges(
    "orchestrator", assign_workers, ["chef_worker"]
)

orchestrator_worker_builder.add_edge("chef_worker", "synthesizer")
orchestrator_worker_builder.add_edge("synthesizer", END)

orchestrator_worker = orchestrator_worker_builder.compile()


if __name__ == "__main__":
    state = orchestrator_worker.invoke({
        "meals": "Please prepare Italian pasta, Mexican tacos, Indian curry, Thai stir-fry, and American burgers"
    })
    print(state["final_menu_guide"])

